import React from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lora } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

const lora = Lora({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const htmlClasses = [
    geistSans.variable,
    geistMono.variable,
    lora.variable,
    'antialiased'
  ].join(' ');

  const bodyClasses = [
    geistSans.className,
    geistMono.className,
    lora.className
  ].join(' ');

  return (
    <html lang="en" className={htmlClasses}>
      <body suppressHydrationWarning={true} className={bodyClasses}>
        <div className="min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
